-- MySQL Script generated by MySQL Workbench
-- Sat Jan  5 19:20:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS mydb ;

-- -----------------------------------------------------
-- Table `mydb`.`JefeProyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.JefeProyecto (
  cod_jefeproyecto INT NOT NULL,
  nombre VARCHAR(45) NULL,
  direccion VARCHAR(45) NULL,
  tlfn INT NULL,
  PRIMARY KEY (cod_jefeproyecto));


-- -----------------------------------------------------
-- Table `mydb`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Proyecto (
  cod_proyecto INT NOT NULL,
  nombre VARCHAR(45) NULL,
  PRIMARY KEY (cod_proyecto));


-- -----------------------------------------------------
-- Table `mydb`.`dirige`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.dirige (
  cod_jefeproyecto INT NOT NULL,
  cod_proyecto INT NOT NULL,
  PRIMARY KEY (cod_jefeproyecto, cod_proyecto),
  CONSTRAINT cod_jefeproyecto
    FOREIGN KEY (cod_jefeproyecto)
    REFERENCES mydb.JefeProyecto (cod_jefeproyecto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT cod_proyecto
    FOREIGN KEY (cod_proyecto)
    REFERENCES mydb.Proyecto (cod_proyecto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX cod_proyecto_idx ON mydb.dirige (cod_proyecto ASC);

-- -----------------------------------------------------
-- Table `mydb`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.plano (
  cod_plano INT NOT NULL,
  fecha_entrega DATE NULL,
  arquitecto VARCHAR(45) NULL,
  dibujo_plano VARCHAR(45) NULL,
  num_figuras INT NULL,
  PRIMARY KEY (cod_plano));


-- -----------------------------------------------------
-- Table `mydb`.`Proyecto_plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Proyecto_plano (
  cod_proyecto INT NOT NULL,
  cod_plano INT NOT NULL,
  PRIMARY KEY (cod_proyecto, cod_plano),
  CONSTRAINT cod_proyecto
    FOREIGN KEY (cod_proyecto)
    REFERENCES mydb.Proyecto (cod_proyecto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT cod_plano
    FOREIGN KEY (cod_plano)
    REFERENCES mydb.plano (cod_plano)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

  CREATE INDEX cod_plano_idx ON mydb.Proyecto_plano (cod_plano ASC);

-- -----------------------------------------------------
-- Table `mydb`.`figura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.figura (
  cod_figura INT NOT NULL,
  nombre VARCHAR(45) NULL,
  color VARCHAR(45) NULL,
  PRIMARY KEY (cod_figura));


-- -----------------------------------------------------
-- Table `mydb`.`tiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.tiene (
  cod_plano INT NOT NULL,
  cod_figura INT NOT NULL,
  PRIMARY KEY (cod_plano, cod_figura),
  CONSTRAINT cod_plano
    FOREIGN KEY (cod_plano)
    REFERENCES mydb.plano (cod_plano)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT cod_figura
    FOREIGN KEY (cod_figura)
    REFERENCES mydb.figura (cod_figura)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

  CREATE INDEX cod_figura_idx ON mydb.tiene (cod_figura ASC);

-- -----------------------------------------------------
-- Table `mydb`.`Linea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Linea (
  id_linea INT NOT NULL,
  Longitud INT NULL,
  puntos INT NULL,
  PRIMARY KEY (id_linea));


-- -----------------------------------------------------
-- Table `mydb`.`poligono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.poligono (
  id_linea INT NOT NULL,
  cod_figura INT NULL,
  num_lineas INT NULL,
  PRIMARY KEY (id_linea),
  CONSTRAINT id_linea
    FOREIGN KEY (id_linea)
    REFERENCES mydb.Linea (id_linea)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT cod_figura
    FOREIGN KEY (cod_figura)
    REFERENCES mydb.figura (cod_figura)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

  CREATE INDEX cod_figura_idp ON mydb.poligono (cod_figura ASC);

-- -----------------------------------------------------
-- Data for table `mydb`.`JefeProyecto`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO mydb.JefeProyecto (cod_jefeproyecto, nombre, direccion, tlfn) VALUES (12, 'pepe', NULL, 645789);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Proyecto`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO mydb.Proyecto (cod_proyecto, nombre) VALUES (321, 'aire');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`dirige`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO mydb.dirige (cod_jefeproyecto, cod_proyecto) VALUES (12, 321);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`plano`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO mydb.plano (cod_plano, fecha_entrega, arquitecto, dibujo_plano, num_figuras) VALUES (333, NULL, 'ramon', NULL, 8);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Proyecto_plano`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO mydb.Proyecto_plano (cod_proyecto, cod_plano) VALUES (321, 333);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`figura`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO mydb.figura (cod_figura, nombre, color) VALUES (111, 'trapecio', 'azul');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`tiene`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO mydb.tiene (cod_plano, cod_figura) VALUES (333, 111);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Linea`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO mydb.Linea (id_linea, Longitud, puntos) VALUES (222, 20, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`poligono`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO mydb.poligono (id_linea, cod_figura, num_lineas) VALUES (222, 111, 4);

COMMIT;


