-- MySQL Script generated by MySQL Workbench
-- Sat Jan  5 02:16:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- Actualizacion de la tabla construccion
START TRANSACTION;
UPDATE mydb.construccion SET cp = 37207;
UPDATE mydb.construccion SET m2_solar = 500,fecha_construccion = '2010-09-01' WHERE numero = 23;
UPDATE mydb.construccion SET m2_solar = 600,fecha_construccion = '2011-06-01' WHERE numero = 24;
UPDATE mydb.construccion SET m2_solar = 750,fecha_construccion = '2011-12-22' WHERE numero = 25;
COMMIT;

-- Actualizacion de la tabla vivienda_unifamiliar
START TRANSACTION;
UPDATE mydb.vivienda_unifamiliar SET m2_construidos = 537 WHERE numero = 24;
UPDATE mydb.vivienda_unifamiliar SET m2_construidos = 700 WHERE numero = 25;
COMMIT;

-- Actualizacion de la tabla bloque
START TRANSACTION;
UPDATE mydb.bloque SET nombre = 'Rosario' , m2_totales = 480 WHERE numero = 23;
COMMIT;



